### ISSUE TITLE
프로젝트 초기환경 설정

### ISSUE THREAD

**Issue by gogoyong** [gogoyong/TreeView#1]
## Description
프로젝트 초기환경 설정

## Todo List
- [ ] issue, PR 템플릿 추가
- [ ] label 및 milestone, project 등 github 설정
- [ ] commit 규칙(convention), eslint, prettier 설정

## Estimated Time
1시간
